[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.6.6"
euclid = "0.22.7"
cassowary = "0.3.0"
itertools = "0.10.5"
textwrap = "0.16.0"
rusttype = "0.9.3"
